version: '3'

services:
  qmk_api:
    build: ./qmk_api
    ports:
    - "5001:5000"
    environment:
      PYTHONUNBUFFERED: 1
      REDIS_HOST: redis
      RELOAD: 1
      S3_HOST: http://minio:9000
      S3_ACCESS_KEY: minio_dev
      S3_SECRET_KEY: minio_dev_secret
      UPDATE_API: 'true'
    volumes:
    - ./qmk_api:/qmk_api
    - ./qmk_compiler:/qmk_compiler

  qmk_api_tasks:
    build: ./qmk_api_tasks
    command: /bin/true
    ports:
     - "5002:5000"
    environment:
      PYTHONUNBUFFERED: 1
      REDIS_HOST: redis
      RELOAD: 1
      S3_HOST: http://minio:9000
      S3_ACCESS_KEY: minio_dev
      S3_SECRET_KEY: minio_dev_secret
      UPDATE_API: 'true'
    volumes:
      - ./qmk_api_tasks:/qmk_api_tasks
      - ./qmk_compiler:/qmk_compiler

  qmk_bot:
    build: ./qmk_bot
    environment:
      #DISCORD_WEBHOOK_URL: <Your private webhook URL>
      PYTHONUNBUFFERED: 1
      REDIS_HOST: redis
      RELOAD: 1
      S3_HOST: http://minio:9000
    volumes:
    - ./qmk_bot:/qmk_bot
    - ./qmk_compiler:/qmk_compiler

  qmk_compiler:
    build: ./qmk_compiler
    environment:
      MINIO_ACCESS_KEY: minio_dev
      MINIO_SECRET_KEY: minio_dev_secret
      PYTHONUNBUFFERED: 1
      REDIS_HOST: redis
      RELOAD: 1
      S3_HOST: http://minio:9000
    volumes:
    - ./qmk_compiler:/qmk_compiler

  qmk_configurator:
    image: node:11.12
    command: /bin/bash -c "yarn && yarn run serve"
    working_dir: /srv/configurator
    ports:
      - "5000:8080"
    volumes:
      - ./qmk_configurator:/srv/configurator

  minio:
    image: minio/minio:RELEASE.2018-12-27T18-33-08Z
    volumes:
     - minio_data:/data
    ports:
     - "9000:9000"
    environment:
      MINIO_ACCESS_KEY: minio_dev
      MINIO_SECRET_KEY: minio_dev_secret
      PYTHONUNBUFFERED: 1
      S3_ACCESS_KEY: minio_dev
      S3_SECRET_KEY: minio_dev_secret
    command: server minio_data
    restart: always

  redis:
    image: redis:4.0
    # For some reason this doesn't seem to work...  I still get:
    # `# Warning: no config file specified, using the default config.`
    #volumes:
    # ./redis contains a redis.conf file, /usr/local/etc/redis/
    # is supposedly where redis looks for its conf
    # - ./redis/:/usr/local/etc/redis/
    ports:
     - "6379:6379"
    restart: always

volumes:
    minio_data:
